import type { Metadata } from 'next';
import { Inter, Space_Grotesk } from 'next/font/google';
import localFont from 'next/font/local';
import { Analytics } from "@vercel/analytics/next"
import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const spaceGrotesk = Space_Grotesk({ subsets: ['latin'], variable: '--font-space' });

const satoshi = localFont({
  src: [
    { path: '../public/assets/Satoshi-Light.otf', weight: '300', style: 'normal' },
    { path: '../public/assets/Satoshi-Regular.otf', weight: '400', style: 'normal' },
    { path: '../public/assets/Satoshi-Medium.otf', weight: '500', style: 'normal' },
    { path: '../public/assets/Satoshi-Bold.otf', weight: '700', style: 'normal' },
    { path: '../public/assets/Satoshi-Black.otf', weight: '900', style: 'normal' },
    { path: '../public/assets/Satoshi-LightItalic.otf', weight: '300', style: 'italic' },
    { path: '../public/assets/Satoshi-Italic.otf', weight: '400', style: 'italic' },
    { path: '../public/assets/Satoshi-MediumItalic.otf', weight: '500', style: 'italic' },
    { path: '../public/assets/Satoshi-BoldItalic.otf', weight: '700', style: 'italic' },
    { path: '../public/assets/Satoshi-BlackItalic.otf', weight: '900', style: 'italic' },
  ],
  variable: '--font-jakarta' // Keeping same variable name to avoid breaking tailwind config
});

export const metadata: Metadata = {
  title: "Formia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${spaceGrotesk.variable} ${satoshi.variable} font-sans antialiased`}
      >
        {children}
        <Analytics />
      </body>
    </html>
  );
}
